using UnityEngine;
using TMPro;
using FMODUnity;

public class Audio_Keyboard : MonoBehaviour
{
    TMP_InputField input;
    private int previousTextLength; 

    public void Start()
    {
        input = GetComponent<TMP_InputField>();
        if (input != null)
        {
            previousTextLength = input.text.Length;
        }
    }

    public void OnValueChanged()
    {
        if (input == null) return;

        int currentTextLength = input.text.Length;

        if (currentTextLength == 0)
        {
            RuntimeManager.PlayOneShot("event:/UI/UI_Keyboard_Error");
        }
        else if (currentTextLength > previousTextLength && Input.anyKeyDown) 
        {
            RuntimeManager.PlayOneShot("event:/FOL/FOL_Keyboard");
        }
        else if (currentTextLength < previousTextLength) 
        {
            RuntimeManager.PlayOneShot("event:/UI/UI_Keyboard_Delete");
        }

        previousTextLength = currentTextLength;
    }

    //All code generated by 
    //© 2025 Sacha "Soul" Epry - 2025. All rights reserved.
    //This software contains original source code developed by Sacha "Soul" Epry.
    //All rights to the code are reserved unless otherwise stated.

}